### ISSUE TITLE
OMP: Info #276: omp_set_nested routing deprecated, please use omp_set_max_active_levels instead.

### ISSUE THREAD

**Issue by weberam2** [daducci/AMICO#123] opened 2021-11-18 01:22 UTC
When running "ae.fit()"
I get a ton of "OMP: Info #276: omp_set_nested routing deprecated, please use omp_set_max_active_levels instead." messages... but it still seems to run.
Any idea how to fix or turn this message off?

Cheers,

Alex W

**Comment by daducci** [comment] 2021-12-29 10:12
Hi, sorry for the delay, just saw the message. I've never seen this message before, so can you please let us know your platform and the version of AMICO where this happpens? Thanks!

**Comment by qiuziru** [comment] 2022-01-11 06:11
Hi，I also encountered the same problem on Linux. I just installed AMICO, which should be the latest version. I am also curious whether this will affect the result and how to fix it. Thanks！

**Comment by daducci** [comment] 2022-01-11 08:52
Thanks @qiuziru for your feedback! Actually, we cannot reproduce the issue, but it should only be a warning and not affect the results. Can you please provide us with more information concerning your environment (e.g., os version, python version etc)?

**Comment by qiuziru** [comment] 2022-01-11 15:07
Thanks for your early reply! I am using Ubuntu 18.04.6 and python 3.8.8. I compared the parameters generated by myself with the expected output, and each voxel has an deviation ranging from 0.002 to 0.015. Is this deviation within the normal range? Thank you very much for your help!

**Comment by MarioOcampo** [comment] 2022-01-12 09:52
Hello @weberam2 and @qiuziru ,
I'm trying to reproduce the error you reported, thank you for letting us know about it. I have some questions.   
What version of OMP do you have? you can check it with the command `echo | cpp -fopenmp -dM | grep -i open`

@qiuziru, 
what model are you using? 
did you create a synthetic signal to evaluate the results? if yes, can I ask you how? 
for which parameters did you report the deviation? 

Best regards
Mario

**Comment by qiuziru** [comment] 2022-01-12 10:09
@MarioOcampo ,
Hello, I used the NODDI model. I ran the command you gave me and got the following results：#define _OPENMP 201511. 
And when I checked, I found that I didn't install DIPY, SPAMS and Camino. Could it be that this led to the warning and inaccurate results? Are all these softwares necessary to use NODDI model? 
I just visualized the image I generated and simply compared some voxel values with the sample output. 
Thank you sincerely for your help!

**Comment by daducci** [comment] 2022-01-17 10:22
As far as I understand, it is a warning (not an error) due to the deprecation of an `OMP` function, which is not properly handled by the `joblib` library. This should not affect the results but in case only the fitting time (I can only speculate, though, as I cannot reproduce it). @qiuziru , the discrepancies you have noted are probably due to normal differences among platforms, compilers, etc, and should not affect your analyses.

**Comment by qiuziru** [comment] 2022-01-17 11:18
Thank you for your help and thank you for developing such a useful tool! @daducci 

Cheers,

Qiuziru

**Comment by daducci** [comment] 2022-01-17 13:16
Hi @weberam2 , in case you still need to suppress the warning, did you try with the following snipped of code?
```python
import warnings
warnings.filterwarnings("ignore")```

**Comment by daducci** [comment] 2022-03-26 16:26
Hey @weberam2 ,

did you try the latest version? The problem should be fixed now, as a new version of SPAMS was released which takes this into account.

**Closed** 2022-04-07 06:45 UTC
Labels: question
