### ISSUE TITLE
ImportError: No module named amico

### ISSUE THREAD

**Issue by RuitingZhang** [daducci/AMICO#70] opened 2018-11-12 11:38 UTC
Hi,

I used conda and created a virtual environment(python2.7), and installed dipy, spams, camino and amico. I had not got any errors during installation. 
When trying to import amico, I got this error:

(dipy-amico) /amico$ python
Python 2.7.15 |Anaconda, Inc.| (default, Oct 23 2018, 18:31:10) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import amico
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named amico

I also tried to add the amico path to the pythonpath, but it didn't work.
I examined the site-package directory and found a directory named "amico-1.0.dist-info", but there was no .py files in it. Does this mean the installation failed?
what should I do?

Thanks!

**Comment by daducci** [comment] 2018-11-14 11:03
Duplicate of #68

**Closed by daducci** 2018-11-14 11:03 UTC
Labels: duplicate
