### ISSUE TITLE
ImportError: No module named _spams_wrap

### ISSUE THREAD

**Issue by liuna0630** [daducci/AMICO#64] opened 2018-04-10 14:17 UTC
Hi,
when i  import spams,i got this error,can you tell me where going wrong?
ImportError                               Traceback (most recent call last)
<ipython-input-3-2eecc34cc6d3> in <module>()
----> 1 import spams

/home/liuna/src/spams-2.6.1/spams.py in <module>()
      7 import six.moves
      8
----> 9 import spams_wrap
     10 import numpy as np
     11 import scipy.sparse as ssp

/home/liuna/src/spams-2.6.1/spams_wrap.py in <module>()
     22         except ImportError:
     23             return importlib.import_module('_spams_wrap')
---> 24     _spams_wrap = swig_import_helper()
     25     del swig_import_helper
     26 elif _swig_python_version_info >= (2, 6, 0):

/home/liuna/src/spams-2.6.1/spams_wrap.py in swig_import_helper()
     21             return importlib.import_module(mname)
     22         except ImportError:
---> 23             return importlib.import_module('_spams_wrap')
     24     _spams_wrap = swig_import_helper()
     25     del swig_import_helper

/usr/lib/python2.7/importlib/__init__.pyc in import_module(name, package)
     35             level += 1
     36         name = _resolve_name(name[level:], package, level)
---> 37     __import__(name)
     38     return sys.modules[name]

ImportError: No module named _spams_wrap

thx

**Comment by daducci** [comment] 2018-11-14 11:02
Duplicate of #68

**Closed by daducci** 2018-11-14 11:02 UTC
Labels: duplicate

**Comment by XuQingLi** [comment] 2024-08-23 02:55
ImportError: No module named '_spams_wrap'
1. `$find / -name "_spams_wrap*" 2>/dev/null `
Here is my result: 
 /t9k/mnt/.conda/envs/WSI/lib/python3.11/site-packages/_spams_wrap.cpython-311-x86_64-linux-gnu.so   it's means u can find it on web ,but OS doesn't know the path.
2. `export LD_LIBRARY_PATH=/t9k/mnt/.conda/envs/WSI/lib/python3.11/site-packages:$LD_LIBRARY_PATH   `  then,  `source /etc/bash.bashrc `  
3.  if u want to be a valid permanetly , export to the env valid  ` vim /etc/bash.bashrc  ` `source /etc/bash.bashrc`, valid after restart
